---
- name: Ansibox will prepare you
  hosts: localhost
  connection: local

  roles:
    - { role: base_osx, when: "ansible_os_family == 'Apple'"  }
    - { role: base_fedora, when: "ansible_distribution == 'Fedora'"  }
    - dotfiles
