---
- name: install gcc
  command: xcode-select --install creates=/usr/bin/gcc

# Assuming homebrew is already installed...
- name: update homebrew
  homebrew: update_homebrew=yes

- name: install homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew.taps

- name: install homebrew packages
  homebrew: name={{ item }} state=upgraded
  with_items: homebrew.packages

- name: install homebrew casks
  homebrew_cask: name={{ item }} state=installed
  with_items: homebrew.casks

- name: discover current shell
  command: dscl . -read /Users/jkeating UserShell
  register: usershell
  changed_when: false

# this will prompt for password :/
- name: set zsh as shell
  command: dscl . change /Users/jkeating UserShell /bin/bash /usr/local/bin/zsh
  sudo: true
  when: not usershell.stdout|search('zsh')

# oh-my-zsh
- name: clone oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       dest=~/.oh-my-zsh
